config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :edit, :destroy]
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  validates :title, length: { maximum: 50  }
  validates :body, length: { maximum: 50 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :introduction, presence: false, length: {maximum: 50}
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!, except: [:top, :about]

    def after_sign_in_path_for(resource)
    	user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
    	root_path
    end
    
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!, except: [:top, :about]
  
  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  	  redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
      @books = Book.all
      @user = current_user
      render action: :index
    end
  end

  def index
    @user = current_user
  	@books = Book.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @book_new = Book.new
  	@book = Book.find(params[:id])
    @user =current_user
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	   redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
        render "edit"
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
   end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController


  def search
  	@model = params["search"]["model"]
  	@content = params["search"]["content"]
  	@how = params["search"]["how"]
  	@datas = search_for(@how,@model,@content)
  end

  private
  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{content}%")
    end
  end
    def backward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!, except: [:top, :about]
  before_action :baria_user, only: [:edit, :update]






  def show
    @book = Book.new
  	@user = User.find(params[:id])
  	@books = @user.books.page(params[:page]).reverse_order
  end

  def edit
  	   @user = User.find(params[:id])
       if @user == current_user
          render "edit"
        else
          redirect_to books_path
        end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "successfully updated user!"
    else
      render "edit"
    end
  end

  def index
  	@users = User.all
    @user = current_user
    @book = Book.new
  end
# email追加してみた
  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end

  def book_params
        params.require(:book).permit(:title, :body)
  end

  # urlを直接入力しても行けない
  def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="edit">
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
	<% if @book.errors.any? %>
  	  <div id="error_explanation" class="alert alert-danger">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
       </div>
<% end %>

  <h5>Title</h5>
  <%= f.text_field :title,class:"col-xs-12" %>
  <h5>Body</h5>
  <%= f.text_area :body,class:"col-xs-12" %>

  <%= f.submit '  Update Book  ',class: "col-xs-12 btn btn-primary" %>
<% end %>

<%= link_to "Show", @book, class: "book_#{@book.id}" %> |
<%= link_to "Back",books_path %>


</div>

app/views/books/index.html.erb
<div class="box">
<div class="container">
<div class="row">
  <div class= "col-xs-3">
  
    <%=  notice %>
    <h2>User info</h2>

      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
      <table class="table table-hover">
        <tr>
        <td><h5>name</h5></td>
        <td><%= @user.name %></td>
        </tr>
        <tr>
          <td><h5>introduction</h5></td>
          <td><%= @user.introduction %></td>
        </tr>
      </table>
        <%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>


    <div class="new book">
    <h2>New book</h2>

      


    <%= form_for(@book, url: books_path) do |f| %>

    <% if @book.errors.any? %>
      <div class="alert alert-warning">
       <h5><%= @book.errors.count %>errors prohibited this book from being saved:</h5>
          <ul>
           <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
      </div>
    <% end %>

      <h5>Title</h5>
    <%= f.text_field :title,class: "col-xs-12" %>

      <h5>Opinion</h5>
    <%= f.text_area :body,class: "col-xs-12" %>
    <br>
    <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    <% end %>
    
  </div>

  </div>


    <div class="col-xs-9">
      <h1>Books</h1>

      

        <table class='table table-hover'>
          <thead>
          <tr>
            <td></td>
            <td><strong>Title</strong></td>
            <td><strong>Opinion</strong></td>
          </tr>
          </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user_id) do %><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg",size:'20x20' %></td>
            <% end %>
            <td><%=link_to book.title, book_path(book.id) %></td>
            <td><%=link_to book.body %></td>
          </tr>
        </tbody>
        <% end %>
        </table>
    </div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="box">
<div class="container">
<div class="row">
<div class= "col-xs-3">
		<%=  notice %>
		<h2>User info</h2>


      <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "100x100" %>

      <table class="table table-hover">
      	<tr>
      	  <td><h5>name</h5></td>
      	  <td><%= @book.user.name %></td>
      	</tr>
      	<tr>
      	  <td><h5>introduction</h5></td>
      	  <td><%= @book.user.introduction %></td>
      	</tr>
      </table>

      <p><%= link_to "", edit_user_path(@book.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>

<div class="newbook">

  <h2>New book</h2>
    <%= form_for(@book_new, url: books_path) do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title,class: "col-xs-12" %>

      <h5>Opinion</h5>
      <%= f.text_area :body,class: "col-xs-12" %>
    <br>
      <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    <% end %>
  </div>
	</div>






	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class='table'>
			<tr>
			<td>
				<%= link_to user_path(@book.user_id) do %>
				<%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'50x50',format: 'no_image.jpg' %>
					<nav>
						<%= @book.user.name %>
					</nav>
				<% end %>
			</td>

			<td><%= link_to @book.title %></td>
			<td><%= @book.body %></td>
			<% if @book.user_id == current_user.id %>
			<td><%= link_to "Edit",edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
			<!-- destroy反応した -->
			<td><%= link_to "Destroy",book_path(@book.id),class:"btn-sm btn-danger", method: :delete,data: {confirm: "削除しますか？"} %></td>
			<% end %>
			</tr>
			</table>

	</div>
</div>
</div>
</div>

app/views/homes/about.html.erb
<h1 class="about">Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
	<%= render 'layouts/notifications' %>

	<div class="box">


		<div class='container'>
		<div class="row">
			<div class='top col-md-offset-3 col-md-6'>
	<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers </strong> !!</h1>

	<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers,</strong></p>

	<p>you can share and exchange your opinions ,inpressions ,and emostions</p>
	<p>bout various books!</p>



	<div class="btn-wrapper">
		<div class="row">
		</div>
	<div class="btn-wrapper">
		<div class="row">
	  	<p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
	    </div>

	    <div class="row">
      <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
     </div>
	  	</div>
	  	</div>
	  	</div>
	</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
    <nav class="navbar navbar-inverse">
      <ul class="nav navbar-nav navbar-left">

        <div class="bookers">Bookers</div>
      </ul>
      <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="">
        <!-- ↓以下のコードは後ほど変更 -->
        <%= link_to 'Home', user_path(current_user.id),class:"glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <!-- 以下のコードは後ほど変更 -->
        <%= link_to 'Users', users_path,class:"glyphicon glyphicon-user" %>
      </li>
      <li class="">
        <!-- 以下のコードは後ほど変更 -->
        <%= link_to 'Books', books_path,class:"glyphicon glyphicon-book" %>
      </li>
      <li class="">
        <%= link_to "logout ", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out" %>
      </li>
    <% else %>
      <li class="">
        <!-- ↓以下のコードは後ほど変更 -->
        <%= link_to " Home ",root_path, class:"glyphicon glyphicon-home" %>
        </li>
      <li class="">
        <a class="glyphicon glyphicon-link "href="/home/about"> About </a>
      </li>
      <li class="">
        <a class="glyphicon glyphicon-edit "href="/users/sign_up"> sign up </a>
      </li>
      <li class="">
        <a class="glyphicon glyphicon-log-in "href="/users/sign_in"> login </a>
      </li>
    <% end %>
  </ul>
    </nav>
  <% if user_signed_in? %>
  <ul class="navbar-right form">
    <%= render 'searchs/search_form' %>
  </ul>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/searchs/_search_form.html.erb
    <div class="search-form">
      <%= form_tag(searchs_search_path, method: :get) do %>
        <%= text_field_tag 'search[content]' %>
        <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
        <%= submit_tag '検索', class: "btn btn-primary" %>
      <% end %>
    </div>

app/views/searchs/search.html.erb
    <% if @model == 'user' %>

				<h2> Users search for<strong>'<%= @content %>'</strong></h2>
				<div class="box">
				<table class="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
							<th colspan="3"></th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% if @datas.any? %>
							<% @datas.each do |data| %>
								<tr class="searched-box">
									<%= link_to user_path(data) do %>
									<td class="images">
										<%= attachment_image_tag data, :profile_image, class: "inline-box", fallback: "no_image.jpg",size:'40x40' %>
									</td>
									<% end %>
									<td class="profiles"><%= data.name %></td>
									<td><%= link_to "Show", user_path(data.id), class: "user_#{data.id}" %></td>

								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
				</div>

			<% else @model == 'book' %>

				<h2> Books search for<strong>'<%= @content %>'</strong></h2>
				<div class="box">
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
					<% if @datas.any? %>
							<% @datas.each do |data| %>
								<tr class="searched-box">
									<td class ="images">
								          <%= attachment_image_tag(data.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg",size:'40x40') %>
								    </td>
									<td><%= link_to data.title, book_path(data.id), class: "book_#{data.id}" %></td>
										<td><%= data.body %></td>
								</tr>
							<% end %>
					<% end %>
					</tbody>
				</table>
	            </div>
			<% end %>

app/views/users/edit.html.erb
<div class="box">
<h2>User  info</h2>

    <%= form_for(@user, url:user_path(current_user.id)) do |f| %>

    <% if @user.errors.any? %>
    <h3 class="red"><%= pluralize(@user.errors.count, "error") %>prohibited this user from being saved:</h3>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li class="red"><%= message %></li>
        <% end %>
    </ul>
<% end %>

      <h4>Name</h4>
    <%= f.text_field :name %>
      <h4>Image</h4>
    <!-- %= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"% -->

    <%= f.attachment_field :profile_image %>
    <h4>introduction</h4>
    <%= f.text_area :introduction %>

    <%= f.submit "Update User" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="box">
<div class="container">
<div class="row">
  <div class= "col-xs-3">
    <h2>User info</h2>


      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>


      <table class="table table-hover">
        <tr>
          <td><h5>name</h5></td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td><h5>introduction</h5></td>
          <td><%= @user.introduction %></td>
        </tr>
      </table>

          <p><%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>


<div class="newbook">
  <h2>New book</h2>
    <%= form_for(@book, url: books_path) do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title,class: "col-xs-12" %>

      <h5>Opinion</h5>
      <%= f.text_area :body,class: "col-xs-12" %>
    
      <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    
    <% end %>
  </div>

  </div>


  <div class= "col-xs-9">
  	<table class='table table-hover' >
      <thead>
  		<tr>
  		<td><strong>image</strong></td>
  		<td><strong>name</strong></td>
      <td></td>
  		</tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg",size:'40x40' %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= link_to"Show",user_path(user.id) %>
        </td>
      </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="box">
<div class="container">
<div class="row">

	<div class="col-xs-3">
		<div class="info">
			<%= render 'layouts/notifications' %>
  		<h2>User info</h2>


  			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>

  			<table class="table table-hover">
  				<tr>
  					<td><h5>name</h5></td>
  					<td><%= @user.name %></td>
  				</tr>
  				<tr>
  					<td><h5>introduction</h5></td>
  					<td><%= @user.introduction %></td>
  				</tr>
  			</table>
    		<p><%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
    	</div>




<div class="newbook">
	<h2>New book</h2>
		<%= form_for(@book, url: books_path) do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>
  		<h5>Title</h5>
  		<%= f.text_field :title,class: "col-xs-12" %>

  		<h5>Opinion</h5>
  		<%= f.text_area :body,class: "col-xs-12" %>
 	
  		<%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
		
		<% end %>
</div>
</div>


<div class="col-xs-9">
	<h2>Books</h2>
	<table class='table table-hover table-inverse'>
		<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
		</thead>


		<% @books.each do |book| %>
		<%= link_to user_path(@user.id) do %>
		<tbody>
		<tr>
		<td><%= attachment_image_tag book.user, :profile_image, :fill, 30, 30,fallback: "no_image.jpg",size:'30x30',format: 'no_image.jpg' %></td>
		<% end %>
		<td><%=link_to book.title, book_path(book.id) %></td>
		<td><%= book.body %></td>
		</td>
		</tr>
		</tbody>
		<% end %>
		</table>
		</div>
</div>
</div>
</div>